### ISSUE TITLE
no notifaction sound

### ISSUE THREAD

**Issue by pugrex** [StevenJDH/Amazon-Stock-Tracker#1]
Hey there, first of all thank you for sharing this program. Im trying it for amazon.com.tr When i add in stock item the program dont send me notifaction sound. What should i do? And i cant change the size of program

**Comment by StevenJDH** [comment]
You will only get alerted if an item goes from `Out of Stock` to `In-Stock`. However, you can test to see if notifications are working by going to `Tools > Test Notifications`, and if there is an item in the list with an `In-Stock` status, you will hear the alert along with any email and SMS services you have configured. Does this help?

The program size if fixed for now, but I may make this sizable later on for the first release or a future release.

**Comment by pugrex** [comment]
Oh great. i can hear the alert now. Thanks a lot!

**Comment by pugrex** [comment]
Oh i forgot to ask. Is it possible to copy the link or open the link when item goes in stock? That would be great but im not sure if this can be done or not

**Comment by StevenJDH** [comment]
Happy to hear, and thanks for trying out the app. 

Having it open links automatically and randomly like that would be intrusive, but I do plan to enable double-clicking on items in the list to take you directly to the product page, which is a similar idea. 

Since your issue is resolved, I will go ahead and close the case.
