### ISSUE TITLE
Captcha

### ISSUE THREAD

**Issue by pugrex** [StevenJDH/Amazon-Stock-Tracker#4]
Hi how can we avoid captcha? Im currently facing captcha on amazon japan and turkey

**Comment by StevenJDH** [comment]
I've been looking into it, but it's completely random when this happens. Once I understand better what triggers the Captcha, I can adapt the code to avoid it. For me, it only happened with the China and USA pages, but in all cases it's temporary. From what I have seen, if you wait a certain amount of time, you will no longer get it. In the case of the USA, it was an hour, and for China, it was about a day or two or a bit longer. 

If you learn anything new, please feel free to share. It may also help to set the check interval to a higher amount like 5 minutes instead of the default 2. Sorry I can't give you a better answer at this time.

**Comment by pugrex** [comment]
I just set it to 4.5 minutes. I'll try hope it works. It may help if the bot checks stocks with different proxies. But it will cost a bit i guess

**Comment by StevenJDH** [comment]
Let's see, but just remember to wait until you no longer get the captcha before checking on interval or it won't go away until you do. As for the proxy idea, I believe you can use external apps like multiproxy if its still around or something newer with a list of free proxy addresses to accomplish the same since this can be configured at the system level. However, one interesting point is that the Captcha is not triggered by your IP or location. In other words, I did tests while being blocked with Chrome, Firefox, and cURL in a console window, and I was still able to connect. Even more interesting is that with cURL I could kind of trigger the captcha on demand and avoid it by playing with the user agent. For example, the below tests I did while being blocked:

Triggers captcha:

```
curl https://www.amazon.cn/dp/B07WF8BK8D
```

Doesn't trigger captcha (but in some cases it does):

```
curl -H "user-agent: Mozilla/5.0 (Windows NT 10.0; rv:87.0) Gecko/20100101 Firefox/87.0" https://www.amazon.cn/dp/B07WF8BK8D
```

But even this was not a very reliable test since it didn't always work, but it was as close to the cause as I got.
