### ISSUE TITLE
Download .Net

### ISSUE THREAD

**Issue by star9695** [StevenJDH/Amazon-Stock-Tracker#5]
I'm installing exe and after opening exe but it said onyl download .Net. I did. Not change

**Comment by StevenJDH** [comment]
> I'm installing exe and after opening exe but it said onyl download .Net. I did. Not change

This is Window's way of saying you are missing the needed runtime. In the past I had a similar issue, you must download the `.NET Desktop Runtime` and not the `.NET Runtime` for version 5x in order for the application to run.

Also worth noting, version 1.0.0 is broken due to a change on Amazon's website, so even if you get it to run it will not work properly. I've already committed the fixes to support Amazon's latest changes and upgraded to .NET 6, so if you want to clone and build the exe, this will work better, otherwise, you will have to wait for the next bug fix release, which should happen soon.

**Comment by star9695** [comment]
I would be very happy if you update it soon. Because I really need this right now. The reason for this is that amazon sites restricted sales to my country after 1 May. That's why the products that amazon sells or sends are not sold and sent to my country. But during the day, sometimes the sales of some products are opened with very little stock. But you understand that it is impossible to find and keep this time. That's why I needed a program like this. Because I was trying to buy affordable products and sell them in my country. Also, it would be great if you add the option to choose the country where the product will be sent and choose the seller as a feature. If you can help me, I'd definitely like to buy some coffees for you. I also installed .net 6 but still got the same error. but But .net 5, open the exe. But as you said, there is a problem in updating the products. I will try to try again. Thank you very much for your information.

**Comment by StevenJDH** [comment]
> I would be very happy if you update it soon. Because I really need this right now. The reason for this is that amazon sites restricted sales to my country after 1 May. That's why the products that amazon sells or sends are not sold and sent to my country. But during the day, sometimes the sales of some products are opened with very little stock. But you understand that it is impossible to find and keep this time. That's why I needed a program like this. Because I was trying to buy affordable products and sell them in my country. Also, it would be great if you add the option to choose the country where the product will be sent and choose the seller as a feature. If you can help me, I'd definitely like to buy some coffees for you. I also installed .net 6 but still got the same error. but But .net 5, open the exe. But as you said, there is a problem in updating the products. I will try to try again. Thank you very much for your information.

I'll do my best to release soon, but these days my free time to develop personal projects is very limited.

With regards to the feature for choosing sending destination, this will not be implemented as it would require integration with Amazon's official product data APIs for sellers. And for the choosing a seller feature, this might come in the distant future in a similar form. Currently, Amazon is the only supported seller and shipper at the moment, or whatever the official provider is for a particular country since not all use Amazon directly, for example, India.

.NET 6 Desktop Runtime is only for the unreleased version that has the needed fixes for Amazon. In other words, you will have to build the source code if you want to use the unreleased version with .NET 6, or wait for an official release.

In the meantime, if you need something sooner, I don't know what countries you require, but there are plenty of alternatives online with different features, some might even have the ones you mentioned above. For example, this one is pretty famous https://camelcamelcamel.com but the notification features and country support is limited.

Let me know if I've answered all your questions, and if so, I'll move to close this ticket.

**Comment by star9695** [comment]
It would be nice if at least a selection could be made according to the country to which the product will be sent. For example, the product is sold on amazon.com and appears in stock. But when it is not sent to my country, there is no point in having it in stock. I've seen some bots that do this. But I couldn't find it. It would be great to know when stock opens in my country from amazon.com. I don't know if this is hard to do.

**Comment by StevenJDH** [comment]
For the moment, this feature won't be implemented, but I will look at it in the future and if it is something I can implement with current approach.

**Comment by star9695** [comment]
Thank you again you can close sir

**Comment by StevenJDH** [comment]
Closed as answered, please open a new issue if more support is needed.
